services:
  mysql:
    image: mysql:8.0.32
    container_name: algafood-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: algafood
      TZ: America/Sao_Paulo
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p1234", "-e", "SHOW DATABASES;" ]
      interval: 20s
      timeout: 10s
      retries: 6
      start_period: 60s
  algafood-redis:
    image: redis:7.4.3-alpine
    networks:
      - network
  algafood-api:
    image: amauricastro/algafood-api
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - network
    depends_on:
      mysql:
        condition: service_healthy
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - algafood-api
volumes:
  mysql-data:

networks:
  network:
    driver: bridge
